version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda
      #- rm Miniconda3-latest-Linux-x86_64.sh
      - echo 'export PATH="~/miniconda/bin:$PATH"' >> ~/.bashrc
      - source ~/.bashrc
      - conda -q update -n base -c defaults conda
      - conda -q init bash

      - conda -q create --yes -n dbacademy python=3.9
      - conda -q activate dbacademy
      - pip -q install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml=reports/unit-tests.xml
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  unit-tests:
    files: unit-tests.xml
    base-directory: reports/
    file-format: JUNITXML
