version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - sudo dnf check-update --releasever=2022.0.20220928
      - sudo yum install -y python3-venv
      - python3.6 -m venv test_env
      - . test_env/bin/activate
      - pip install --upgrade pip
      - pip -q install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml=reports/unit-tests.xml
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  unit-tests:
    files: unit-tests.xml
    base-directory: reports/
    file-format: JUNITXML
