version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml ./reports/unit-tests.xml
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  report:
    unit-tests:
      files: "reports/unit-tests.xml"
      file-format: "JUNITXML"
