version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - python -m venv test_env
      - . test_env/bin/activate
      - pip -q install --upgrade pip
      - pip -q install .
      - pip -q install -r requirements.txt --use-pep517
  build:
    commands:
      - python -m pytest --junit-xml=reports/unit-tests.xml --ignore=test
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  unit-tests:
    files: unit-tests.xml
    base-directory: reports/
    file-format: JUNITXML
