version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -c "print('Hello Nurse!')"
      - cd src
      - python -m xmlrunner discover -s ../test -t ../test --output ../reports/unit-tests
  post_build:
    commands:
      - echo Build completed on `date`

reports:
#  coverage:
#    files:
#      - "coverage/*"
#    base-directory: 'test-reports'
#    discard-paths: yes
report:
  unit-tests:
    files: "reports/unit-tests/*"
    file-format: "JUNITXML"
